Repository Picnic-GSM/GOOUT, pull requests merged in 2021-09, with the labels that each got.

#2 Feature/early leave goout add
  GOOUT.xcodeproj/project.pbxproj
  GOOUT/Assets.xcassets/GOOUT_CheckButtonImage.imageset/Contents.json
  GOOUT/Assets.xcassets/GOOUT_CheckButtonImage.imageset/Rectangle 29.png
  GOOUT/Assets.xcassets/GOOUT_GooutAddButtonImage.imageset/Contents.json
  GOOUT/Assets.xcassets/GOOUT_GooutAddButtonImage.imageset/signin_Btn.svg
  GOOUT/Assets.xcassets/GOOUT_SelectedCheckButtonImage.imageset/Contents.json
  GOOUT/Assets.xcassets/GOOUT_SelectedCheckButtonImage.imageset/Group 55.png
  GOOUT/Assets.xcassets/GOOUT_UnderButtonImage.imageset/Contents.json
  GOOUT/Assets.xcassets/GOOUT_UnderButtonImage.imageset/Path 3.svg
  GOOUT/Controller/AddViewController.swift
  GOOUT/Controller/InquiryByGradeViewController.swift
  GOOUT/Controller/MyClassInquiryViewController.swift
  Podfile.lock
Labels: code-review, Complete

#8 Feature/early leave goout add
  GOOUT/Assets.xcassets/GOOUT_GooutAddButtonImage.imageset/Contents.json
  GOOUT/Assets.xcassets/GOOUT_GooutAddButtonImage.imageset/signin_Btn.png
  GOOUT/Assets.xcassets/GOOUT_GooutAddButtonImage.imageset/signin_Btn.svg
  GOOUT/Controller/AddViewController.swift
Labels: urgent, code-review, Complete

#10 Feature/forgot password
  GOOUT.xcodeproj/project.pbxproj
  GOOUT/Controller/ForgotPasswordViewController.swift
  GOOUT/SceneDelegate.swift
  Podfile.lock
Labels: code-review

#7 Feature/signin
  GOOUT.xcodeproj/project.pbxproj
  GOOUT/AppDelegate.swift
  GOOUT/Controller/SigninVIewController.swift
  GOOUT/Extension/Extension.swift
  GOOUT/SceneDelegate.swift
Labels: code-review, Complete

#9 회원가입 페이지 퍼블리싱 완료
  GOOUT.xcodeproj/project.pbxproj
  GOOUT.xcodeproj/xcshareddata/xcschemes/GOOUT.xcscheme
  GOOUT/Controller/SignUpViewController.swift
  GOOUT/SceneDelegate.swift
Labels: code-review, Complete

#12 Feature/password window
  GOOUT.xcodeproj/project.pbxproj
  GOOUT/Controller/ShowPasswordViewController.swift
  GOOUT/SceneDelegate.swift
Labels: urgent, code-review, Complete

#14 코드 입력 화면 퍼블리싱 끝났습니당
  GOOUT/Assets.xcassets/GOOUT_Logo.imageset/Contents.json
  GOOUT/Assets.xcassets/GOOUT_Logo.imageset/Image.png
  GOOUT/Controller/EnterDistributioncode.swift
  GOOUT/View/WriteCodeTextfieldView.swift
Labels: code-review, Complete

#13 인증번호 입력 화면 개발 완료
  GOOUT.xcodeproj/project.pbxproj
  GOOUT/Controller/TestViewController.swift
  GOOUT/View/getAuthCodeView.swift
Labels: code-review, Complete

#11 Feature/inquiry for each class
  GOOUT.xcodeproj/project.pbxproj
  GOOUT/Assets.xcassets/GOOUT_Cancel.imageset/Contents.json
  GOOUT/Assets.xcassets/GOOUT_Cancel.imageset/추가 버튼.svg
  GOOUT/Assets.xcassets/GOOUT_CancelBtn.imageset/Contents.json
  GOOUT/Assets.xcassets/GOOUT_CancelBtn.imageset/추가버튼.svg
  GOOUT/Assets.xcassets/GOOUT_Undraw_image_post.imageset/Contents.json
  GOOUT/Assets.xcassets/GOOUT_Undraw_image_post.imageset/undraw_image_post_24iy 1.svg
  GOOUT/Controller/InquiryByGradeViewController.swift
  GOOUT/Controller/InquiryForEachClassViewController.swift
  GOOUT/Controller/MyClassInquiryViewController.swift
  GOOUT/View/Cell/PleaseCheckYourReturnHomeTableCell.swift
  GOOUT/View/Cell/requestConfirmationCell.swift
  GOOUT/View/EarlyLeaveTimeToGoOutView.swift
  GOOUT/View/OutConditionView.swift
  GOOUT/View/RequestInquiryForEachClassModel.swift
  GOOUT/View/RequestStatus.swift
  GOOUT/View/noHistoryView .swift
  Podfile.lock
Labels: documentation, enhancement, code-review

#16 Feature/list by grade
  GOOUT.xcodeproj/project.pbxproj
  GOOUT/Assets.xcassets/GOOUT_AnyStudentDoNotGoImage.imageset/Contents.json
  GOOUT/Assets.xcassets/GOOUT_AnyStudentDoNotGoImage.imageset/GOOUT_AnyStudentDoNotGoImage.png
  GOOUT/Assets.xcassets/GOOUT_GradeUnderButtonImage.imageset/Contents.json
  GOOUT/Assets.xcassets/GOOUT_GradeUnderButtonImage.imageset/GOOUT_GradeUnderButtonImage.svg
  GOOUT/Controller/InquiryByGradeViewController.swift
  GOOUT/View/AnyStudentDoNotGoView.swift
  GOOUT/View/EarlyLeaveListHeaderView.swift
  GOOUT/View/EarlyLeaveListTableCell.swift
  GOOUT/View/OutListHeaderView.swift
  GOOUT/View/OutListTableCell.swift
  GOOUT/View/StateExplainView.swift
  Podfile.lock
Labels: urgent, code-review, Complete

#17 Feature/early leave goout add
  GOOUT/Controller/AddViewController.swift
  GOOUT/Controller/SignUpViewController.swift
  GOOUT/Extension/Extension.swift
  GOOUT/SceneDelegate.swift
  Podfile.lock
Labels: urgent, Complete

#18 개발 완료호호~
  GOOUT/Controller/AddViewController.swift
Labels: urgent, Complete

#20 Develop
  GOOUT/Controller/ForgotPasswordViewController.swift
  GOOUT/Controller/ShowPasswordViewController.swift
  GOOUT/Controller/SignUpViewController.swift
  GOOUT/Controller/SigninVIewController.swift
  GOOUT/Controller/TestViewController.swift
  GOOUT/SceneDelegate.swift
Labels: Incomplete

#23 Feature/inquiry for each class
  GOOUT.xcodeproj/project.pbxproj
  GOOUT/Controller/InquiryForEachClassViewController.swift
  GOOUT/View/Cell/PleaseCheckYourReturnHomeTableCell.swift
  GOOUT/View/Cell/requestConfirmationCell.swift
  GOOUT/View/EarlyLeaveTimeToGoOutView.swift
  Podfile.lock
Labels: documentation, code-review, Complete

#26 Feature/lunch
  GOOUT/Assets.xcassets/GOOUT_LunchScreenImage.imageset/Contents.json
  GOOUT/Assets.xcassets/GOOUT_LunchScreenImage.imageset/looogo.png
  GOOUT/Base.lproj/LaunchScreen.storyboard
Labels: Complete

#27 Feature/my page
  GOOUT.xcodeproj/project.pbxproj
  GOOUT/Assets.xcassets/GOOUT_LogOutImage.imageset/Contents.json
  GOOUT/Assets.xcassets/GOOUT_LogOutImage.imageset/undraw_fast_car_p4cu.svg
  GOOUT/Controller/MyPageViewController.swift
  GOOUT/SceneDelegate.swift
Labels: Complete

#24 Feature/information
  GOOUT.xcodeproj/project.pbxproj
  GOOUT/Controller/InformationViewController.swift
  GOOUT/SceneDelegate.swift
  GOOUT/View/numberCellView.swift
  Podfile.lock
Labels: code-review, Complete

#33 리스트 셀 높이 키우기
  GOOUT/Controller/InquiryByGradeViewController.swift
  Podfile.lock
Labels: urgent, hotfix, Complete

#35 간격 줄이기
  GOOUT/Controller/InformationViewController.swift
  GOOUT/Controller/InquiryByGradeViewController.swift
  GOOUT/Controller/SignUpViewController.swift
  Podfile.lock
Labels: urgent, hotfix, Complete

#36 Signin 페이지 추가 및 수정
  GOOUT/Controller/SigninVIewController.swift
  Podfile.lock
Labels: Complete

#37 information page objc func 코드 위치 조절
  GOOUT/Controller/InformationViewController.swift
  Podfile.lock
Labels: bug, urgent, hotfix

#40 dropDown 연결
  GOOUT/Controller/InquiryByGradeViewController.swift
Labels: urgent, hotfix, Complete

#46 모달과 tableView Cell 연결
  GOOUT/Controller/InquiryByGradeViewController.swift
  Podfile.lock
Labels: urgent, Complete

#47 cornerRadius 해결
  GOOUT/Controller/InquiryByGradeViewController.swift
Labels: bug, urgent, hotfix, Complete

#49 Feature/list modal
  GOOUT/Controller/InquiryByGradeViewController.swift
  GOOUT/View/GooutEarlyLeaveInfoView.swift
  Podfile.lock
Labels: urgent, Complete

#55 모달 수정
  GOOUT/Controller/InquiryByGradeViewController.swift
Labels: urgent, hotfix, Complete

#48 Feature/sign up
  GOOUT.xcodeproj/project.pbxproj
  GOOUT/Controller/SignInUp/SignUpViewController.swift
  GOOUT/View/emailTextFieldView.swift
Labels: urgent, code-review, Complete

#66 numberCellView
  GOOUT.xcodeproj/project.pbxproj
  GOOUT/View/Cell/numberCellView.swift
Labels: bug, urgent, hotfix, Complete

#68 완료!!
  GOOUT.xcodeproj/project.pbxproj
  GOOUT/Controller/Main/InquiryByGradeViewController.swift
  GOOUT/Controller/SignInUp/PutInformationViewController.swift
  GOOUT/Controller/SignInUp/SignUpViewController.swift
  Podfile.lock
Labels: hotfix, Complete
